// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eavqklvphtsvfwdthwxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhdnFrbHZwaHRzdmZ3ZHRod3hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTY5OTcsImV4cCI6MjA2NjY3Mjk5N30.gRtmG5mfVGMn_muZIcrBjRK3FwviDgaiFdqTWaGCNcU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);